In [1]:
import random as rd
import pandas as pd
import getpass as ps

In [2]:
app_list = []
df = pd.DataFrame()

In [61]:
def edu_email():
    email = input("Please enter your @student.hult.edu email: ")
    if '@student.hult.edu' in email: 
        return email
    else:
        return edu_email()

In [54]:
def new_user(): 
   
    email = str(edu_email())


    #---------------------------------------------------------------------------
    
    user_name = input("Enter your user name: ")
    pass_word = ps.getpass("Password: ")
    
    #---------------------------------------------------------------------------

    
                
    nation = input("What is your nationality? ")
    
    #---------------------------------------------------------------------------
    
    while True:
        
        lang_no = int(input("How many languages do you speak? (Max 5) "))
    
        if lang_no == 1:
            lang_1 = input("What language do you speak? ")
            lang_2 = ""
            lang_3 = ""
            lang_4 = ""
            lang_5 = ""
            break
        
        elif lang_no == 2:
            lang_1 = input("What language do you speak? ")
            lang_2 = input("What is the second language you speak? ")
            lang_3 = ""
            lang_4 = ""
            lang_5 = ""
            break
        
        elif lang_no == 3:
            lang_1 = input("What language do you speak? ")
            lang_2 = input("What is the second language you speak? ")
            lang_3 = input("What is the third language you speak? ")
            lang_4 = ""
            lang_5 = ""
            break
        
        elif lang_no == 4:
            lang_1 = input("What language do you speak? ")
            lang_2 = input("What is the second language you speak? ")
            lang_3 = input("What is the third language you speak? ")
            lang_4 = input("What is the fourth language you speak? ")
            lang_5 = ""
            break
        
        else:
            lang_1 = input("What language do you speak? ")
            lang_2 = input("What is the second language you speak? ")
            lang_3 = input("What is the third language you speak? ")
            lang_4 = input("What is the fourth language you speak? ")
            lang_5 = input("What is the fifth language you speak? ")
            break
            
    #---------------------------------------------------------------------------
    
    
    app_list.append({"user_name" : user_name,
                     "password" : pass_word,
                     "email" : email,
                     "nation" : nation,
                     "lang_no" : lang_no,
                     "lang_1" : lang_1,
                     "lang_2" : lang_2,
                     "lang_3" : lang_3,
                     "lang_4" : lang_4,
                     "lang_5" : lang_5})
    

    print("Account Created")

In [55]:
def old_user():
    user_name = input("Enter your user name: ")
    pass_word = ps.getpass("Password: ")
    #if u_name == user_data['username']: #and pswd == user_data['password']:
    
    while True:
        if str(user_name) in str(user_data['user_name']) and str(pass_word) in str(user_data['password']):
            print(f"Login successful, Welcome back {user_name}!")
            break
    
        else:
            print("Invalid login, please try again.")
            return old_user()
        
    #else:
        #print("User doesn't exist or wrong password!")

In [62]:
#defining if user is new or old
#def login():
while True:
    user = input("""  
    If you are an existing user, input 'Log In'

    If you are a new user, input 'Register'  

    """)

    if user.lower() == "register" :
        new_user()
        user_data = df.append(app_list, ignore_index = True)
        user_data = user_data.reindex(columns = ['user_name', 'password', 'email', 'nation', 'lang_no', 'lang_1', "lang_2", "lang_3", "lang_4", "lang_5"])
        user_data.to_excel('user_data.xlsx')
        break


    elif user.lower() == "log in":
        old_user()
        break


    else:
        print("Wrong input! Please enter 'Log In' or 'Register'")

    If you are an existing user, input 'Log In'

    If you are a new user, input 'Register'

    register
Please enter your @student.hult.edu email: ioasjdfoiasj
Please enter your @student.hult.edu email: asdfasaoj@student.hult.edu
Enter your user name: ajsdfijaso
Password: ········
What is your nationality? iosadjfois
How many languages do you speak? (Max 5) 1
What language do you speak? asdfoijo
Account Created

In [63]:
user_data

,user_name,password,email,nation,lang_no,lang_1,lang_2,lang_3,lang_4,lang_5
0,raafi,raafi,raafi@gmail.com,raafi,2,raafi,raafi,,,
1,renee,renee,renee,renee,3,renee,renee,renee,,
2,jess,jess,jess@jess.com,jess,2,jess,jess,,,
3,raafi,raafi,None,raafi,2,raafi,raafi,,,
4,raafi,raafi,None,raaaaaaafi,2,asdf,asdf,,,
5,renee,adsf,renee@student.hult.edu,asdf,2,adsf,safd,,,
6,marcelo,marcelo1,None,marcelo,3,asdf,asdf,asdf,,
7,ayelet,adsf,ayelet@student.hult.edu,adsf,3,asdf,adsf,adsf,,
8,jess,jess,jess@student.hult.edu,asdf,3,asd,asdf,asdf,,
9,chase,adsf,None,asdf,2,asd,fasdf,,,
10,renee,renee,renee@student.hult.edu,renee,3,asdf,asdf,adsf,,
11,renee,reneeeee,None,asdfasdf,2,asdf,adsf,,,
12,asdf,sadf,None,asdf,2,asd,asdf,,,
13,asdfasdfffff,asfdf,asf,asdfads,2,asdfds,asdfadsfasd,,,
14,ajsdfijaso,asojfasdoifj,asdfasaoj@student.hult.edu,iosadjfois,1,asdfoijo,,,,

In [ ]:
app_list

In [ ]:
df